<a href="https://colab.research.google.com/github/SelvamRaju/Natural-Language-Processing-LSTM/blob/main/NLP_LSTM_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP-LSTM-Part-1

### Domain : Digital content and entertainment industry

In [1]:
# Imports
import numpy as np
from keras.preprocessing import sequence
from tensorflow.keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, Embedding, Conv1D, GlobalMaxPool1D, LSTM, TimeDistributed, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences

1. Import and analyse the data set.
Hint: - Use `imdb.load_data()` method
- Get train and test set
- Take 10000 most frequent words


In [2]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000, maxlen=300)

In [3]:
X_train.shape

(19051,)

In [4]:
X_test.shape

(19450,)

In [5]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [7]:
#Printing unique labels
np.unique(y_train)

array([0, 1])

In [8]:
# Max length of seq. in X_train
max(len(i) for i in X_train)

299

In [9]:
# Max length of seq. in X_test
max(len(i) for i in X_test)

299

2. Perform relevant sequence adding on the data


In [10]:
# Mean of X_train data
np.mean([len(i) for i in X_train])

159.67697233741012

The maximum length of a review in the data set it 159 and so padding the data to 200

In [11]:
#padding -  200 length
X_train_padded = sequence.pad_sequences(X_train, maxlen=200)
X_test_padded = sequence.pad_sequences(X_test, maxlen=200)

3. Perform following data analysis:

  • Print shape of features and labels
  
  • Print value of any one feature and it's label


In [12]:
print("Number of reviews in X_train : ", len(X_train))
print("Number of reviews in X_test  : ", len(X_test))

Number of reviews in X_train :  19051
Number of reviews in X_test  :  19450


In [13]:
# Printing the number of words in random two review as a sample - Note : padded to 200

print("1st reveiw in dataset", X_train_padded[0].shape[0])
print("100th reveiw in dataset", X_train_padded[99].shape[0])

1st reveiw in dataset 200
100th reveiw in dataset 200


In [14]:
print("Value 50th review : ", X_train[49])
print("Label of 50th review : ", y_train[49])

Value 50th review :  [1, 13, 286, 1017, 76, 5, 8, 30, 1202, 13, 161, 40, 14, 22, 4, 86, 58, 187, 21, 149, 12, 174, 5, 13, 5372, 15, 45, 1932, 646, 252, 45, 6, 31, 975, 22, 21, 45, 6, 163, 3288, 10, 10, 294, 5618, 15, 12, 100, 30, 128, 398, 5, 12, 100, 30, 13, 104, 14, 22, 69, 4, 986, 8, 30, 6, 120, 4, 350, 61, 3242, 2, 21, 19, 6, 189, 3232, 305, 7, 6, 2408, 1038, 45, 6, 1053, 1434, 19, 43, 6, 227, 53, 487, 12, 100, 30, 6, 356, 4, 362, 26, 9673, 225, 57, 282, 138, 36, 144, 2, 23, 8, 3584, 972, 39, 4, 578, 1007, 12, 62, 28, 77, 87, 8, 67, 68, 649, 2, 13, 124, 45, 6, 212, 21, 45, 117, 3855, 15, 3138, 4, 52, 108, 39, 4, 530, 10, 10, 3584, 765, 9, 210, 253, 5, 1728, 24, 8, 760, 2, 175, 58, 59, 5852, 25, 80, 99, 45, 254, 8, 3296, 6, 22, 54, 4, 293, 109, 9, 38, 1220, 5, 12, 66, 9, 41, 1382, 92, 387, 41, 272, 2418, 25, 83, 536, 15, 442, 49, 432, 7, 2, 73, 59, 9, 21, 442, 6, 327, 31, 4, 432, 7, 415, 1390, 387, 168, 103, 129, 362, 586, 387, 41, 3107, 18, 98, 151, 10, 10, 474, 386, 743, 12, 6, 14

4. Decode the feature value to get original sentence


In [15]:
#Getting word index from IMDB
imdb_word_index = imdb.get_word_index()

In [16]:
index_from = 3
imdb_word_index = {key:value + index_from for key, value in imdb_word_index.items()}
imdb_word_index['the']

4

In [17]:
inverted_word = {value: key for key, value in imdb_word_index.items()}
[inverted_word[index] for index in X_train[50] if index > index_from]

['if',
 "you're",
 'a',
 'fan',
 'of',
 'film',
 'noir',
 'and',
 'think',
 'they',
 "don't",
 'make',
 "'em",
 'like',
 'they',
 'used',
 'to',
 'here',
 'is',
 'your',
 'answer',
 'they',
 'just',
 "don't",
 'make',
 "'em",
 'in',
 'hollywood',
 'anymore',
 'we',
 'must',
 'turn',
 'to',
 'the',
 'french',
 'to',
 'remember',
 'how',
 'satisfying',
 'subtle',
 'and',
 'terrific',
 'a',
 'well',
 'made',
 'film',
 'from',
 'that',
 'genre',
 'can',
 'be',
 'read',
 'my',
 'lips',
 'is',
 'a',
 'wonderfully',
 'nasty',
 'little',
 'gift',
 'to',
 'the',
 'faithful',
 'from',
 'director',
 'jacques',
 'featuring',
 'sharp',
 'storytelling',
 'and',
 'fine',
 'performances',
 'from',
 'and',
 'vincent',
 'br',
 'br',
 'the',
 'basic',
 'plot',
 'could',
 'have',
 'been',
 'written',
 'in',
 'the',
 "40's",
 'dumb',
 'but',
 'appealing',
 'ex',
 'con',
 'and',
 'a',
 'smart',
 'but',
 'femme',
 'fatale',
 'who',
 'turns',
 'out',
 'to',
 'be',
 'ambitious',
 'discover',
 'each',
 'other',



*  Result 1 for Positive Review
*  Result 2 for Negative Review

In [18]:
y_train[50]

1

Review @ 50th in the data is Postive

5. Design, train, tune and test a sequential model.

  Hint: The aim here Is to import the text, process it such a way that it can be taken as an inout to the ML/NN
classifiers. Be analytical and experimental here in trying new approaches to design the best model.


In [19]:
vocabulary = 10000
max_words = 200

model = Sequential()
model.add(Embedding(vocabulary, 100, input_length=max_words))
model.add(LSTM(100,return_sequences= True))
dense_layer = Dense(100, activation='relu')
model.add(TimeDistributed(dense_layer))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [20]:
#Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [21]:
#Model Summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 100)          1000000   
                                                                 
 lstm (LSTM)                 (None, 200, 100)          80400     
                                                                 
 time_distributed (TimeDistr  (None, 200, 100)         10100     
 ibuted)                                                         
                                                                 
 flatten (Flatten)           (None, 20000)             0         
                                                                 
 dense_1 (Dense)             (None, 1)                 20001     
                                                                 
Total params: 1,110,501
Trainable params: 1,110,501
Non-trainable params: 0
______________________________________________

In [22]:
#Model Fitting
model.fit(X_train_padded, y_train, epochs=5, batch_size=50)

Epoch 1/5
382/382 [==============================] - 99s 252ms/step - loss: 0.3634 - accuracy: 0.8258
Epoch 2/5
382/382 [==============================] - 95s 248ms/step - loss: 0.1778 - accuracy: 0.9332
Epoch 3/5
382/382 [==============================] - 96s 252ms/step - loss: 0.0983 - accuracy: 0.9637
Epoch 4/5
382/382 [==============================] - 96s 253ms/step - loss: 0.0611 - accuracy: 0.9786
Epoch 5/5
382/382 [==============================] - 94s 247ms/step - loss: 0.0386 - accuracy: 0.9856


In [23]:
#Printing scores and accuracy
scores, accuracy = model.evaluate(X_test_padded, y_test, verbose=0)
print("Score :", scores)
print("Accuracy :", accuracy)

Score : 0.6416922211647034
Accuracy : 0.8547557592391968


6. Use the designed model to print the prediction on any one sample.

In [28]:
positiveReview = "i liked this wonderful movie"
negatvieReview = "i did not like this awkward movie"

In [29]:
for review in [positiveReview, negatvieReview]:
    encoded_review = []
    review_split = review.split(" ")
    for word in review_split:
        encoded_review.append(imdb_word_index[word])
    review_padded = pad_sequences([encoded_review], maxlen=200)
    pred = model.predict(review_padded)
    if pred > 0.5:
        typeOfReview = 'Positive Review'
    else:
        typeOfReview = 'Negative Review'
    print("Review : ", review)
    print("Type of Review : ", typeOfReview)

Review :  i liked this wonderful movie
Type of Review :  Positive Review
Review :  i did not like this awkward movie
Type of Review :  Negative Review
