<a href="https://colab.research.google.com/github/SelvamRaju/Natural-Language-Processing-LSTM/blob/main/NLP_LSTM_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP-LSTM-Part-1

### Domain : Digital content and entertainment industry

In [18]:
# Imports
import numpy as np
from keras.preprocessing import sequence
from tensorflow.keras.datasets import imdb

1. Import and analyse the data set.
Hint: - Use `imdb.load_data()` method
- Get train and test set
- Take 10000 most frequent words


In [2]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000, maxlen=300)

17473536/17464789 [==============================] - 0s 0us/step


In [3]:
X_train.shape

(19051,)

In [4]:
X_test.shape

(19450,)

In [5]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [8]:
#Printing unique labels
np.unique(y_train)

array([0, 1])

In [11]:
# Max length of seq. in X_train
max(len(i) for i in X_train)

299

In [12]:
# Max length of seq. in X_test
max(len(i) for i in X_test)

299

2. Perform relevant sequence adding on the data


In [14]:
# Mean of X_train data
np.mean([len(i) for i in X_train])

159.67697233741012

The maximum length of a review in the data set it 159 and so padding the data to 200

In [19]:
#padding -  200 length
X_train_padded = sequence.pad_sequences(X_train, maxlen=200)
X_test_padded = sequence.pad_sequences(X_test, maxlen=200)

3. Perform following data analysis:

  • Print shape of features and labels
  
  • Print value of any one feature and it's label


In [21]:
print("Number of reviews in X_train : ", len(X_train))
print("Number of reviews in X_test  : ", len(X_test))

Number of reviews in X_train :  19051
Number of reviews in X_test  :  19450


In [31]:
# Printing the number of words in random two review as a sample - Note : padded to 200

print("1st reveiw in dataset", X_train_padded[0].shape[0])
print("100th reveiw in dataset", X_train_padded[99].shape[0])

1st reveiw in dataset 200
100th reveiw in dataset 200


In [33]:
print("Value 50th review : ", X_train[49])
print("Label of 50th review : ", y_train[49])

Value 50th review :  [1, 13, 286, 1017, 76, 5, 8, 30, 1202, 13, 161, 40, 14, 22, 4, 86, 58, 187, 21, 149, 12, 174, 5, 13, 5372, 15, 45, 1932, 646, 252, 45, 6, 31, 975, 22, 21, 45, 6, 163, 3288, 10, 10, 294, 5618, 15, 12, 100, 30, 128, 398, 5, 12, 100, 30, 13, 104, 14, 22, 69, 4, 986, 8, 30, 6, 120, 4, 350, 61, 3242, 2, 21, 19, 6, 189, 3232, 305, 7, 6, 2408, 1038, 45, 6, 1053, 1434, 19, 43, 6, 227, 53, 487, 12, 100, 30, 6, 356, 4, 362, 26, 9673, 225, 57, 282, 138, 36, 144, 2, 23, 8, 3584, 972, 39, 4, 578, 1007, 12, 62, 28, 77, 87, 8, 67, 68, 649, 2, 13, 124, 45, 6, 212, 21, 45, 117, 3855, 15, 3138, 4, 52, 108, 39, 4, 530, 10, 10, 3584, 765, 9, 210, 253, 5, 1728, 24, 8, 760, 2, 175, 58, 59, 5852, 25, 80, 99, 45, 254, 8, 3296, 6, 22, 54, 4, 293, 109, 9, 38, 1220, 5, 12, 66, 9, 41, 1382, 92, 387, 41, 272, 2418, 25, 83, 536, 15, 442, 49, 432, 7, 2, 73, 59, 9, 21, 442, 6, 327, 31, 4, 432, 7, 415, 1390, 387, 168, 103, 129, 362, 586, 387, 41, 3107, 18, 98, 151, 10, 10, 474, 386, 743, 12, 6, 14

4. Decode the feature value to get original sentence


In [34]:
#Getting word index from IMDB
imdb_word_index = imdb.get_word_index()

1654784/1641221 [==============================] - 0s 0us/step


5. Design, train, tune and test a sequential model.

  Hint: The aim here Is to import the text, process it such a way that it can be taken as an inout to the ML/NN
classifiers. Be analytical and experimental here in trying new approaches to design the best model.


6. Use the designed model to print the prediction on any one sample.